### ISSUE TITLE
Rename project to oim-api

### ISSUE THREAD

**Issue by MarkusTiede** [baloise/oim-api#1]

**Comment by vangual** [comment]
What is the reasoning behind the request?
We can rename the project (and its url) on github to comply however the term oimapi (without the minus) is already hardcoded in a lot of infrastructure parts and documents.

**Comment by MarkusTiede** [comment]
IMHO oimapi might tend to assuming it being a 6-letter acronym instead of a 2xTLA. oim-api sticks to normal [kebap-case](https://winnercrespo.com/naming-conventions/) naming and makes it clearer. Maybe @joachimprinzbach has something to add here?

**Comment by joachimprinzbach** [comment]
Nothing to add. I prefer descriptive names, even oim is, at least for me, hard to remember what it means.

**Comment by MarkusTiede** [comment]
Agreeing why there is #2 .

**Comment by vangual** [comment]
Repository renamed.
As indicated in my previous comment the internal name occurances will not be changed.
